# Generated by Django 2.2.19 on 2023-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230215_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='beautful_prase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
