# Generated by Django 2.2.19 on 2023-02-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230215_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='beautful_prase',
            new_name='beautful_phrase',
        ),
    ]
